name: nitro-maestro-android
on: workflow_dispatch
jobs:
  build:
    runs-on: self-hosted
    env:
      NITRO_API_KEY: ${{ secrets.NITRO_API_KEY }}
    steps:
      - uses: actions/checkout@v3
      - uses: nitro-build/github-action-nitro-android@62290c01827edad07baefdc038357de3beefc04f
        id: nitro
      - name: Install Maestro and run e2e tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 31
          arch: x86_64
          avd-name: emulator
          script: .maestro/run-android.sh "${{ steps.nitro.outputs.nitro-app-path }}" .maestro/android-home-flow.yaml "${{ steps.nitro.outputs.nitro-output-dir }}"/maestro-e2e-report.xml
      - uses: actions/upload-artifact@v3
        with:
          path: ${{ steps.nitro.outputs.nitro-output-dir }}
